core/src/edx/org/openedx/core/ui/theme/Colors.kt
- Add missing color for 2u/develop branch
For Light theme
```
light_tab_unselected_btn_background
light_tab_unselected_btn_content
light_tab_selected_btn_content
light_course_home_header_shade
light_course_home_back_btn_background
light_settings_title_content
light_progress_bar_color
light_progress_bar_background_color
```
For dark theme
```
dark_tab_unselected_btn_background
dark_tab_unselected_btn_content
dark_tab_selected_btn_content
dark_course_home_header_shade
dark_course_home_back_btn_background
dark_settings_title_content
dark_progress_bar_color
dark_progress_bar_background_color
```
=> fix: Add missing color for 2u/develop branch

app/build.gradle
- `apply plugin: 'fullstory'` wrap the plugin with the condition, if the full story is enabled.
=> fix: disable full story plugin when disabled

app/src/main/java/org/openedx/app/AnalyticsManager.kt, app/src/main/java/org/openedx/app/di/ScreenModule.kt, core/src/main/java/org/openedx/core/data/model/CourseEnrollments.kt, core/src/main/java/org/openedx/core/domain/interactor/IAPInteractor.kt, core/src/main/java/org/openedx/core/presentation/IAPAnalytics.kt, core/src/main/java/org/openedx/core/presentation/iap/IAPViewModel.kt, core/src/main/java/org/openedx/core/ui/UpgradeToAccessView.kt, dashboard/src/main/java/org/openedx/courses/presentation/DashboardGalleryView.kt, dashboard/src/main/java/org/openedx/courses/presentation/DashboardGalleryViewModel.kt, dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardListFragment.kt, dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardListViewModel.kt, dashboard/src/test/java/org/openedx/dashboard/presentation/DashboardViewModelTest.kt, profile/src/main/java/org/openedx/profile/presentation/settings/SettingsFragment.kt, profile/src/main/java/org/openedx/profile/presentation/settings/SettingsViewModel.kt
Relates to https://github.com/openedx/openedx-app-android/issues/340
=> fix: Add upgrade banner in the FC47 Primary Course card view

profile/src/main/java/org/openedx/profile/data/model/Account.kt, profile/src/main/java/org/openedx/profile/domain/model/Account.kt, profile/src/main/java/org/openedx/profile/presentation/edit/EditProfileFragment.kt, profile/src/main/res/values/strings.xml
To ensure the app complies with COPPA regulations - [Issue](https://docs.google.com/spreadsheets/d/1YuN7Wg2sqMwQf8R02Z0iLtKhPsq1C4LWklMmR1QU5Cs/edit?gid=36631478#gid=36631478&range=17:17)
- Remove the Year of Birth (YOB) field from the profile section
- If learner's age is more than 13:
- Display toggle for Limited and Full profile
- Allow image upload in both Limited and Full profile
- Display all fields in both Limited and Full profile, except YOB
- Disable the fields in Limited profile
- If learner's age is less than 13 or not provided (`requiresParentalConsent = true`):
- Do not display toggle for Limited profile
- Do not allow image upload, hide the icon
- Display all fields but disable them
Instead of removing the code, I've commented the code, because post-MVP we might be moving …
=> chore: Changes for COPPA compliance removing YOB from profile

app/build.gradle, app/proguard-rules.pro, auth/build.gradle, auth/proguard-rules.pro, build.gradle, core/build.gradle, core/consumer-rules.pro, core/proguard-rules.pro, core/src/main/AndroidManifest.xml, course/build.gradle, course/proguard-rules.pro, dashboard/build.gradle, dashboard/proguard-rules.pro, discovery/build.gradle, discovery/proguard-rules.pro, discussion/build.gradle, discussion/proguard-rules.pro, gradle.properties, profile/build.gradle, profile/proguard-rules.pro, settings.gradle, whatsnew/build.gradle, whatsnew/proguard-rules.pro
[LEARNER-10122](https://2u-internal.atlassian.net/browse/LEARNER-10122)
- Enabled R8/Proguard with full mode.
- Make the signed build acceptable by the Google Play console by fixing the user Permission merging issue.
=> fix: signed build issue with R8 full mode

course/src/main/java/org/openedx/course/presentation/unit/video/VideoUnitFragment.kt, course/src/main/java/org/openedx/course/presentation/unit/video/YoutubeVideoUnitFragment.kt, discovery/src/main/java/org/openedx/discovery/presentation/info/CourseInfoFragment.kt
The PR fixes the following bugs:
- Retain Video Seek Time when Exiting Fullscreen in Native Videos
- Multiple videos were playing simultaneously when appeared in a single unit
- Open in External Browser Pop-Up for Bachelor's Degrees - [Issue](https://docs.google.com/spreadsheets/d/1YuN7Wg2sqMwQf8R02Z0iLtKhPsq1C4LWklMmR1QU5Cs/edit?gid=36631478#gid=36631478&range=77:77)
Multiple Videos Issue - Open these units in the videos tab:
- Unit for Youtube Videos: [The Big Picture](https://learning.edx.org/course/course-v1:RWTHx+MTI003x+1T2024/block-v1:RWTHx+MTI003x+1T2024+type@sequential+block@c784b927d69340de87d6c0d9be8cc678/block-v1:RWTHx+MTI003x+1T2024+type@vertical+block@ba158699b87b4397ae499d36cd25a358)
- Unit for Native Videos: [Feature Scaling - Normalization and …
=> fix: Auto Playing Videos and Discovery's External Browser Pop-Up

course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt, course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerFragment.kt, course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerViewModel.kt
- Handle UI if an unit has zero descendant
- show unit list if a subsection have more then 1 units.
=> fix: Handle units with no descendants

course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineScreen.kt, course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineUIState.kt, course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt, course/src/main/java/org/openedx/course/presentation/videos/CourseVideoViewModel.kt, course/src/test/java/org/openedx/course/presentation/outline/CourseOutlineViewModelTest.kt
The crash was fixed + added UI handlers for the Home and Videos tabs to stop infinite loading
=> fix: crash when internet disconnected right after opening a course

app/src/main/java/org/openedx/app/AnalyticsManager.kt, app/src/main/java/org/openedx/app/analytics/FullstoryAnalytics.kt
Crashlytics Integration with FullStory
- Add a Fullstory session replay link to a crash report.
fixes: [LEARNER-10158](https://2u-internal.atlassian.net/browse/LEARNER-10158)
=> feat: Crashlytics Integration with FullStory

dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardRouter.kt, dashboard/src/main/java/org/openedx/learn/presentation/LearnFragment.kt, dashboard/src/main/java/org/openedx/learn/presentation/LearnViewModel.kt, discovery/src/main/java/org/openedx/discovery/presentation/DiscoveryRouter.kt, discovery/src/main/java/org/openedx/discovery/presentation/NativeDiscoveryFragment.kt, discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryFragment.kt, discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryViewModel.kt, discovery/src/main/java/org/openedx/discovery/presentation/program/ProgramFragment.kt, discovery/src/main/java/org/openedx/discovery/presentation/program/ProgramViewModel.kt
- Remove IconBtn and its implementation from Discovery and Learn toolbar
fix: LEARNER-10138
=> fix: Remove setting button from toolbar

dashboard/src/main/java/org/openedx/courses/presentation/DashboardGalleryView.kt
Displays a dynamic list of primary course buttons, managing up to four views: Due, Future, Upgrade, and Resume. Views are shown in priority order: Due, Future, Upgrade, and Resume.
If all four views are available, the Future view is removed to ensure a maximum of three buttons are displayed. Any unavailable views are omitted from the list, maintaining the defined priority.
| Before | After |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/6cc4cab0-bd4b-4241-97ac-0fa24d8acbec" height=600 /> | <img src="https://github.com/user-attachments/assets/b3c33f91-5250-4ae7-b77e-5ae2a5f6f754"  height=600/> |
=> chore: Limit the number of CTAs on the Primary Card

app/src/main/java/org/openedx/app/data/storage/PreferencesManager.kt, core/src/main/java/org/openedx/core/domain/model/AppConfig.kt
Fix several crashes when app config is not saved in the preferences.
line 22 [doc](https://docs.google.com/spreadsheets/d/1YuN7Wg2sqMwQf8R02Z0iLtKhPsq1C4LWklMmR1QU5Cs/)
=> fix: added default value to the AppConfig to prevent crashes in some cases 

app/src/main/java/org/openedx/app/AppRouter.kt
Added ability to ignore crash when we try to add a fragment at the wrong time. This doesn't affect anything and works when the app in the background state.
=> fix: ignore IllegalStateException when fragment transaction fails

core/build.gradle, course/src/main/java/org/openedx/course/settings/download/DownloadQueueFragment.kt
Fix `IllegalStateException` on `supportFragmentManager.popBackStack()`
- Ensure `MutableStateFlow` is lifecycle-aware by utilizing `collectAsStateWithLifecycle`.
**Steps to reproduce:**
- Login in the app.
- Open any course.
- Start downloading any video.
- Open the video downloading Queue screen.
- Move the app in the background before completing the video download.
- App leads to crash after completing video download when the app is in the background.
**Note:** Make sure the following options are enabled from the Developer options.
- Always show crash dialog.
- Show background ANRs.
=> fix: `IllegalStateException` on `supportFragmentManager.popBackStack()`

core/src/main/java/org/openedx/core/module/TranscriptManager.kt, core/src/main/java/org/openedx/core/utils/Logger.kt
try/catch block was missed for the second case when transcriptInputStream == null
=> fix: catch exception when parsing file for transcripts

course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerFragment.kt
Enable the cast button for HLS videos.
- After the [PR#43](https://github.com/edx/edx-mobile-marketplace-android/pull/43) HLS video can be cast via chrome cast from the app.
=> fix: Enabled cast button for HLS videos

discussion/src/main/java/org/openedx/discussion/presentation/threads/DiscussionAddThreadViewModel.kt
Fixed a crash when trying to retrieve the first element in an empty list
=> fix: crash when trying to get first topic in list

core/src/main/java/org/openedx/core/utils/LocaleUtils.kt
- Due to legal reason we need to remove russia from countries list.
fix: LEARNER-10216
=> fix: Remove russia from editProfile countries list

course/src/main/java/org/openedx/course/presentation/unit/video/EncodedVideoUnitViewModel.kt
Jira: [LEARNER-10231](https://2u-internal.atlassian.net/browse/LEARNER-10231)
Firebase Crash: [EncodedVideoUnitViewModel.onCreate](https://console.firebase.google.com/u/1/project/openedx-mobile/crashlytics/app/android:org.edx.mobile/issues?versions=6.0.3%20(6000003)&state=open&time=last-seven-days&tag=all&sort=eventCount)
Crash on CastContext instance when play services aren't available
- Unable to get CastContext when Google Play services aren’t available, leads to the app crash.
**Steps to reproduce:**
- Log in to the app on the emulator OR real device with no OR disabled Google Play service.
- Open any course, and click on the Videos tab.
- Open any video from the list, and the user is redirected to the video component screen, and 🔥 app crashes.
=> fix: Crash on CastContext instance when play services aren't available

course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerAdapter.kt
- Going forward, all HTML Xblocks will be visible on the mobile side, regardless of `student_view_multi_device`.
fix: LEARNER-10232
=> fix: Remove `student_view_mutli_device` dependency for HTML XBlocks

course/src/main/java/org/openedx/course/presentation/ui/CourseVideosUI.kt
[LEARNER-10248](https://2u-internal.atlassian.net/browse/LEARNER-10248)
Fix crash of `IllegalArgumentException - current must not be NaN` during bulk download.
- Add validation to ensure that the progress value is not NaN.
**Steps to reproduce (specific courses)**
**Variant-1**
- Open the course named `Quantum Mechanics for Scientists and Engineers 1`
- Click on the video tab and start that bulk download.
- Try to expand the sections from the video tab, that lead the app to the crash.
**Variant-2**
- Open the course named `Quantum Mechanics for Scientists and Engineers 1`
- Click on the video tab and start that bulk download.
- Rapidly click on the arrow icon to expand the `section` from the Home tab, and the action leads the app to the crash.
=> fix: crash `current must not be NaN` during bulk download

course/src/main/java/org/openedx/course/presentation/unit/video/VideoFullScreenFragment.kt, course/src/main/java/org/openedx/course/presentation/unit/video/VideoUnitFragment.kt
[LEARNER-10283](https://2u-internal.atlassian.net/browse/LEARNER-10283)
Fix the Inconsistency of `keepScreenOn` to restrict display timeout.
- Replace the `keepScreenOn` property with the activity level flag `FLAG_KEEP_SCREEN_ON`.
=> fix: Inconsistency of `keepScreenOn` to restrict display timeout
